#ifndef TEENSY_REBOOT_SUPPORT_h_
#define TEENSY_REBOOT_SUPPORT_h_

// Reboot support
#define CPU_RESTART_ADDR (uint32_t *)0xE000ED0C
#define CPU_RESTART_VAL 0x5FA0004
#define CPU_RESTART (*CPU_RESTART_ADDR = CPU_RESTART_VAL);

#endif
